require 'talon/ast/number'
require 'talon/ast/boolean'
require 'talon/ast/identifier'
require 'talon/ast/method_call'
require 'talon/ast/sequence'
require 'talon/ast/binary_operator'
require 'talon/ast/bracket_operator'
require 'talon/ast/grouped'
